site_name: Ynu Wiki
site_url: https://ynu09.github.io/ynu-wiki/
theme:
  name: material
  palette:
    primary: 'brown'
  logo: 'images/24.png' # 로고 이미지 경로

nav:
  - 홈: index.md
  - Ubuntu: 
    - Virtual Box 세팅: ubuntu/virtual_box.md