site_name: Ynu Wiki
site_url: https://ynu09.github.io/ynu-wiki/ # 이미지 경로 영향
theme:
  name: material
  palette:
    primary: 'brown'
  logo: '/ynu-wiki/images/24.png' # 로고 이미지 경로

nav:
  - 홈: index.md
  - Ubuntu: 
    - Virtual Box 세팅: ubuntu/virtual_box.md
    - Ubuntu 세팅: ubuntu/setting.md
    - ROS2 Foxy 설치: ubuntu/ros2_foxy.md
  - Website: website.md